### ISSUE TITLE
create category not working in 1.21.5

### ISSUE THREAD

**Issue by SomeTroller77** [Bounser/Nascraft#24]
[13:43:52 ERROR]: Could not pass event InventoryClickEvent to Nascraft v1.9.2
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R3/entity/CraftPlayer
        at Nascraft-1.9.2.jar/me.bounser.anvilgui.version.Wrapper1_21_R3.toNMS(Wrapper1_21_R3.java:33) ~[Nascraft-1.9.2.jar:?]
        at Nascraft-1.9.2.jar/me.bounser.anvilgui.version.Wrapper1_21_R3.getRealNextContainerId(Wrapper1_21_R3.java:23) ~[Nascraft-1.9.2.jar:?]
        at Nascraft-1.9.2.jar/me.bounser.anvilgui.version.Wrapper1_21_R3.newContainerAnvil(Wrapper1_21_R3.java:82) ~[Nascraft-1.9.2.jar:?]
        at Nascraft-1.9.2.jar/me.bounser.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:171) ~[Nascraft-1.9.2.jar:?]
        at Nascraft-1.9.2.jar/me.bounser.anvilgui.AnvilGUI.access$1000(AnvilGUI.java:38) ~[Nascraft-1.9.2.jar:?]
        at Nascraft-1.9.2.jar/me.bounser.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:684) ~[Nascraft-1.9.2.jar:?]
        at Nascraft-1.9.2.jar/me.bounser.nascraft.commands.admin.marketeditor.overview.MarketEditorInvListener.onClickInventory(MarketEditorInvListener.java:102) ~[Nascraft-1.9.2.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:71) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3195) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:59) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:14) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1446) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:175) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1426) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1420) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:118) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1381) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1262) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:308) ~[paper-1.21.5.jar:1.21.5-103-2ba1675]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R3.entity.CraftPlayer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 29 more

**Comment by tearfulDalvik** [comment]
same...

Can't view graphs either

**Comment by llsgllsg** [comment]
Same here...
